### ISSUE TITLE
Error 255 while making data backup

### ISSUE THREAD

**Issue by dogiex** [mauronofrio/android_device_xiaomi_cepheus#1]
Got Error 255 while making data backup.
Using TWRP version 3.3.1-39
![Screenshot_2019-08-25-11-13-58](https://user-images.githubusercontent.com/16224046/63647709-005c9000-c72e-11e9-9cd6-22113941baad.png)

**Comment by mauronofrio** [comment]
I need of a log to understand which is the problem, to take it use this command:
adb shell cat /tmp/recovery.log

copy the output in a filetext or on pastebin and send me it

**Comment by dogiex** [comment]
Here you go.
[recovery[2].log](https://github.com/mauronofrio/android_device_xiaomi_cepheus/files/3538001/recovery.2.log)

**Comment by mauronofrio** [comment]
You have multiple apps or multiple users, before try to do the backup you need to disable them and follow this guide, your user is 999

https://forum.xda-developers.com/oneplus-6/how-to/255-error-twrp-backup-restore-999-t3801632

**Comment by dogiex** [comment]
> You have multiple apps or multiple users, before try to do the backup you need to disable them and follow this guide, your user is 999
> 
> https://forum.xda-developers.com/oneplus-6/how-to/255-error-twrp-backup-restore-999-t3801632

Thanks for the reply and answer. I surely do have dual apps in MIUI. Will check your link. Thanks.
